---
version: '2'
services:
  zookeeper-0:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2022:2181
    restart: unless-stopped

  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2021:2181
    restart: unless-stopped
  
  kafka-0:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-0
      - zookeeper-1

    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-0:2181,zookeeper-1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-0:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: unless-stopped

  kafka-1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-0
      - zookeeper-1
    ports:
      - 39092:39092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-0:2181,zookeeper-1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: unless-stopped

  kafka-2:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-0
      - zookeeper-1
    ports:
      - 49092:49092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-0:2181,zookeeper-1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://localhost:49092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: unless-stopped


  bridge-0:
    image: bridge
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2
    environment:
      MQTT_URI: mqtt.eclipseprojects.io
      MQTT_PORT: 1883
      MQTT_TOPIC: SSC0158-2023-G2-0
      KAFKA_URI: kafka-0
      KAFKA_PORT: 9092
      KAFKA_TOPIC: measurements0
    restart: unless-stopped

  bridge-1:
    image: bridge
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2
    environment:
      MQTT_URI: mqtt.eclipseprojects.io
      MQTT_PORT: 1883
      MQTT_TOPIC: SSC0158-2023-G2-1
      KAFKA_URI: kafka-0
      KAFKA_PORT: 9092
      KAFKA_TOPIC: measurements1
    restart: unless-stopped

  bridge-2:
    image: bridge
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2
    environment:
      MQTT_URI: mqtt.eclipseprojects.io
      MQTT_PORT: 1883
      MQTT_TOPIC: SSC0158-2023-G2-2
      KAFKA_URI: kafka-0
      KAFKA_PORT: 9092
      KAFKA_TOPIC: measurements2
    restart: unless-stopped

